### ISSUE TITLE
Democode in Readme incorrect

### ISSUE THREAD

**Issue by jacob-ruth** [TobogganApps/TAOverlayView#1]
The demo code you have listed for initializing a new TAOverlayView and adding subtracted paths should be in viewDidLayoutSubviews, instead of viewDidAppear, as referenced [here](http://stackoverflow.com/questions/13904205/ios-setcontentoffset-not-working-on-ipad/13904962#13904962) and documented [here](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instm/UIViewController/viewDidLayoutSubviews).  

My program did not properly display it until I made that change.

**Comment by nyapster** [comment]
Thanks for letting me know! I'm currently traveling without my laptop but I will fix it as soon as I return in July.

**Comment by jacob-ruth** [comment]
This was actually my issue triggered by an unrelated modification.
